### ISSUE TITLE
完全按照提供的步骤,无法复现结果

### ISSUE THREAD

**Issue by RandomTuringDuck** [thunlp/Bert2Tag#2]
按照步骤来无法复现这个结果, 测试集里F@3只有0.1 - -!
请问是否有其他的细节没有提供, 比如train.sh里有哪些参数是必须要添加进去的?

**Comment by SunSiShining** [comment]
> 按照步骤来无法复现这个结果, 测试集里F@3只有0.1 - -!
> 请问是否有其他的细节没有提供, 比如train.sh里有哪些参数是必须要添加进去的?

**Comment by RandomTuringDuck** [comment]
写错了,是验证集F@3只有0.1

**Comment by SunSiShining** [comment]
Hi, 谢谢你的问题。请问你是不是把batch size或者accumulate steps改了，导致model没有很好的收敛。我们当时在training dataset上的Epoch Mean Loss=0.0471 (epoch=4), 然后在dev上测试F1@3=0.368, 你可以提供一下目前你的model在training dataset上的Epoch Mean Loss数值吗? 这样我们可以进一步确认问题，并帮助解决。

**Comment by SunSiShining** [comment]
我们在2块Tesla T4(2*16G)上跑的实验，因此直接将batch size调整为其最大容量。如果你使用不同容量的计算卡，我们建议可以稍微调整一下accumulate steps，让model可以充分收敛。如果还有问题欢迎提问，这个issue我们先close了。

**Comment by RandomTuringDuck** [comment]
> 我们在2块Tesla T4(2*16G)上跑的实验，因此直接将batch size调整为其最大容量。如果你使用不同容量的计算卡，我们建议可以稍微调整一下accumulate steps，让model可以充分收敛。如果还有问题欢迎提问，这个issue我们先close了。也可以邮件沟通: [s-sun17@mails.tsinghua.edu.cn](mailto:s-sun17@mails.tsinghua.edu.cn)

非常感谢你的回答,我看了一下我的mean loss确实没有降到你所说的那个值, 可能跟我使用的卡有关,我只用了一张24G的M40。我会再尝试一下,按照你的意见。
